name: Auto-merge pre-commit-ci PRs

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: >-
      ${{ github.actor == 'pre-commit-ci[bot]'
      || github.event.pull_request.user.login == 'pre-commit-ci[bot]' }}
    steps:
      - name: Approve PR
        run: |
          gh pr review "$PR_URL" --approve \
            -b "Automatically approved pre-commit-ci updates"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Enable auto-merge
        run: gh pr merge --auto --rebase --delete-branch "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
